### ISSUE TITLE
glyph rendering

### ISSUE THREAD

**Issue by sidorares** [ericfreese/node-freetype2#2]
hi,
Do you have plans to add rasterization functions to your library? I need font rasterizer for my X11-based ui toolkit ( https://github.com/sidorares/ntk , https://github.com/sidorares/node-x11 ) to be used together with XRender CreateGlyphSet / AddGlyphs / CompositeGlyphs8/16/32 requests. 

Data I need:
  input: font file, font size + dpi (maybe optionally list of glyphs to render)
  output
  - glyps:
     ( w x h x grayscale pixels )
     advance x,y
     line height
  - kerning pairs

If you don't have plans to add this yourself, would you be interested in PR?

**Comment by mattdesl** [comment]
hey @sidorares i'm also interested in this lately (been doing a lot of [bitmap font](https://github.com/mattdesl/text-modules) stuff in JS). I noticed you've been making some progress on your fork; I'd be willing to help out. :+1:

**Comment by sidorares** [comment]
@mattdesl great! I'm currently working on freetype+harfbuzz bindings - output would be glyph bitmaps + positioned glyphs for given utf8 string

**Comment by sidorares** [comment]
main reason for having harfbuzz+freetype together - I'd like to handle complex scripts + a lot of fonts don't have kern table so freetype kerning is useless, harfbuzz gives support for gpos-based kerning

**Comment by mattdesl** [comment]
Sounds ambitious. What about layout for those languages? Something like Pango? 

Just FYI opentype.js has added [basic GPOS kerning](https://github.com/nodebox/opentype.js/pull/20). :smile:

**Comment by sidorares** [comment]
maybe pango later :) given that I already re-implemented xlib+xrender+many others I'm not scared
I'm doing this more to be able learn internals rather then to make production ready library, so I might give a try to make manual layout on top of harfbuzz ( maybe using fribidi ) and after that start using pango
