### ISSUE TITLE
Thoughts on WASM

### ISSUE THREAD

**Issue by Julusian** [ericfreese/node-freetype2#45]
As there are some missing prebuilds (see #44), and node-gyp-build does not play well with electron-builder I was thinking it might be worth looking into whether freetype2 can be compiled into wasm instead.

What are your thoughts?  
I am tempted to give it a try, but have very little experience with wasm

**Comment by aminya** [comment]
Yeah, wasm is useful too. But it is not well supported on some platforms, and it is also slower than native code.

**Comment by Julusian** [comment]
I started looking into it yesterday, but found that wasm lacks any hooks for node garbage collection, meaning it will be very very easy to leak memory unless users of the library explicitly delete objects they no longer need.
It would turn this 'safe' library into something a lot more c like and rather 'unsafe'

So the idea is no longer appealing to me for this
