### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by zumbalogy** [ericfreese/node-freetype2#6]
I have tried with a few different builds of freetype, and of node/iojs. I always seem to get something like this:

npm install freetype2        
|
> freetype2@0.1.2 install /home/sh/testfire/node_modules/freetype2
> node-gyp rebuild

make: Entering directory `/home/sh/testfire/node_modules/freetype2/build'
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftsystem.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftinit.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftdebug.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftbase.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftbbox.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftglyph.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftbdf.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftbitmap.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftcid.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftfstype.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftgasp.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftgxval.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftlcdfil.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftmm.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftotval.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftpatent.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftpfr.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftstroke.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftsynth.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/fttype1.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftwinfnt.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/base/ftxf86.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/bdf/bdf.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/cff/cff.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/cid/type1cid.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/pcf/pcf.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/pfr/pfr.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/sfnt/sfnt.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/truetype/truetype.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/type1/type1.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/type42/type42.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/winfonts/winfnt.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/raster/raster.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/smooth/smooth.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/autofit/autofit.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/cache/ftcache.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/gzip/ftgzip.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/lzw/ftlzw.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/bzip2/ftbzip2.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/gxvalid/gxvalid.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/otvalid/otvalid.o
In file included from ../vendor/freetype/src/otvalid/otvalid.c:29:0:
../vendor/freetype/src/otvalid/otvmod.c: In function ‘otv_validate’:
../vendor/freetype/src/otvalid/otvmod.c:85:31: warning: variable ‘num_glyphs’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
     FT_UInt                   num_glyphs = (FT_UInt)face->num_glyphs;
                               ^
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/psaux/psaux.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/pshinter/pshinter.o
  CC(target) Release/obj.target/libfreetype/vendor/freetype/src/psnames/psnames.o
  AR(target) Release/obj.target/gyp/freetype.a
  COPY Release/freetype.a
  CXX(target) Release/obj.target/freetype2/src/freetype2.o
In file included from ../src/freetype2.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanError(const char*)’:
../node_modules/nan/nan.h:319:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:339:13: note: in expansion of macro ‘_NAN_ERROR’
     return  _NAN_ERROR(v8::Exception::Error, errmsg);
             ^
../node_modules/nan/nan.h: In function ‘void NanThrowError(const char*)’:
../node_modules/nan/nan.h:324:7: error: ‘ThrowException’ is not a member of ‘v8’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
       ^
../node_modules/nan/nan.h:343:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
     ^
../node_modules/nan/nan.h:319:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:324:26: note: in expansion of macro ‘_NAN_ERROR’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                          ^
../node_modules/nan/nan.h:343:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
     ^
../node_modules/nan/nan.h: In function ‘void NanThrowError(v8::Handle<v8::Value>)’:
../node_modules/nan/nan.h:348:5: error: ‘ThrowException’ is not a member of ‘v8’
     v8::ThrowException(error);
     ^
../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanError(const char*, int)’:
../node_modules/nan/nan.h:355:53: error: ‘New’ is not a member of ‘v8::String’
     v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                     ^
../node_modules/nan/nan.h:357:14: error: ‘New’ is not a member of ‘v8::String’
     obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
              ^
../node_modules/nan/nan.h:357:65: error: no matching function for call to ‘v8::Int32::New(const int&)’
     obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
                                                                 ^
../node_modules/nan/nan.h:357:65: note: candidate is:
In file included from /home/sh/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:134,
                 from ../src/freetype2.cc:1:
/home/sh/.node-gyp/0.12.2/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/sh/.node-gyp/0.12.2/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
In file included from ../src/freetype2.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanTypeError(const char*)’:
../node_modules/nan/nan.h:319:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:369:12: note: in expansion of macro ‘_NAN_ERROR’
     return _NAN_ERROR(v8::Exception::TypeError, errmsg);
            ^
../node_modules/nan/nan.h: In function ‘void NanThrowTypeError(const char*)’:
../node_modules/nan/nan.h:324:7: error: ‘ThrowException’ is not a member of ‘v8’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
       ^
../node_modules/nan/nan.h:373:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
     ^
../node_modules/nan/nan.h:319:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:324:26: note: in expansion of macro ‘_NAN_ERROR’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                          ^
../node_modules/nan/nan.h:373:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
     ^
../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanRangeError(const char*)’:
../node_modules/nan/nan.h:319:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:377:12: note: in expansion of macro ‘_NAN_ERROR’
     return _NAN_ERROR(v8::Exception::RangeError, errmsg);
            ^
../node_modules/nan/nan.h: In function ‘void NanThrowRangeError(const char*)’:
../node_modules/nan/nan.h:324:7: error: ‘ThrowException’ is not a member of ‘v8’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
       ^
../node_modules/nan/nan.h:381:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
     ^
../node_modules/nan/nan.h:319:38: error: ‘New’ is not a member of ‘v8::String’
 # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                      ^
../node_modules/nan/nan.h:324:26: note: in expansion of macro ‘_NAN_ERROR’
       v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                          ^
../node_modules/nan/nan.h:381:5: note: in expansion of macro ‘_NAN_THROW_ERROR’
     _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
     ^
../node_modules/nan/nan.h: In constructor ‘NanCallback::NanCallback()’:
../node_modules/nan/nan.h:727:49: error: no matching function for call to ‘v8::Object::New()’
     v8::Local<v8::Object> obj = v8::Object::New();
                                                 ^
../node_modules/nan/nan.h:727:49: note: candidate is:
In file included from /home/sh/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:134,
                 from ../src/freetype2.cc:1:
/home/sh/.node-gyp/0.12.2/deps/v8/include/v8.h:2388:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/sh/.node-gyp/0.12.2/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
In file included from ../src/freetype2.cc:1:0:
../node_modules/nan/nan.h: In constructor ‘NanCallback::NanCallback(const v8::Handle<v8::Function>&)’:
../node_modules/nan/nan.h:733:49: error: no matching function for call to ‘v8::Object::New()’
     v8::Local<v8::Object> obj = v8::Object::New();
                                                 ^
../node_modules/nan/nan.h:733:49: note: candidate is:
In file included from /home/sh/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:134,
                 from ../src/freetype2.cc:1:
/home/sh/.node-gyp/0.12.2/deps/v8/include/v8.h:2388:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/sh/.node-gyp/0.12.2/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
In file included from ../src/freetype2.cc:1:0:
../node_modules/nan/nan.h: In destructor ‘NanCallback::~NanCallback()’:
../node_modules/nan/nan.h:740:12: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Dispose’
     handle.Dispose();
            ^
../node_modules/nan/nan.h:741:12: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Clear’
     handle.Clear();
            ^
../node_modules/nan/nan.h: In member function ‘void NanCallback::SetFunction(const v8::Handle<v8::Function>&)’:
../node_modules/nan/nan.h:181:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:746:39: note: in expansion of macro ‘NanSymbol’
     NanPersistentToLocal(handle)->Set(NanSymbol("callback"), fn);
                                       ^
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Function> NanCallback::GetFunction()’:
../node_modules/nan/nan.h:181:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:750:46: note: in expansion of macro ‘NanSymbol’
     return NanPersistentToLocal(handle)->Get(NanSymbol("callback"))
                                              ^
../node_modules/nan/nan.h:751:25: error: expected primary-expression before ‘>’ token
         .As<v8::Function>();
                         ^
../node_modules/nan/nan.h:751:27: error: expected primary-expression before ‘)’ token
         .As<v8::Function>();
                           ^
../node_modules/nan/nan.h: In member function ‘void NanCallback::Call(int, v8::Handle<v8::Value>*)’:
../node_modules/nan/nan.h:181:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:759:13: note: in expansion of macro ‘NanSymbol’
         Get(NanSymbol("callback")).As<v8::Function>();
             ^
../node_modules/nan/nan.h:759:51: error: expected primary-expression before ‘>’ token
         Get(NanSymbol("callback")).As<v8::Function>();
                                                   ^
../node_modules/nan/nan.h:759:53: error: expected primary-expression before ‘)’ token
         Get(NanSymbol("callback")).As<v8::Function>();
                                                     ^
../node_modules/nan/nan.h:761:9: error: ‘GetCurrent’ is not a member of ‘v8::Context’
         v8::Context::GetCurrent()->Global()
         ^
../node_modules/nan/nan.h: In member function ‘void NanAsyncWorker::SavePersistent(const char*, v8::Local<v8::Object>&)’:
../node_modules/nan/nan.h:181:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:808:17: note: in expansion of macro ‘NanSymbol’
     handle->Set(NanSymbol(key), obj);
                 ^
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Object> NanAsyncWorker::GetFromPersistent(const char*)’:
../node_modules/nan/nan.h:181:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
 #define NanSymbol(value) v8::String::NewSymbol(value)
                          ^
../node_modules/nan/nan.h:815:24: note: in expansion of macro ‘NanSymbol’
     return handle->Get(NanSymbol(key)).As<v8::Object>();
                        ^
../node_modules/nan/nan.h:815:53: error: expected primary-expression before ‘>’ token
     return handle->Get(NanSymbol(key)).As<v8::Object>();
                                                     ^
../node_modules/nan/nan.h:815:55: error: expected primary-expression before ‘)’ token
     return handle->Get(NanSymbol(key)).As<v8::Object>();
                                                       ^
../node_modules/nan/nan.h: In member function ‘virtual void NanAsyncWorker::HandleErrorCallback()’:
../node_modules/nan/nan.h:837:30: error: ‘New’ is not a member of ‘v8::String’
         v8::Exception::Error(v8::String::New(errmsg))
                              ^
../src/freetype2.cc: In function ‘void Init(v8::Handle<v8::Object>)’:
../src/freetype2.cc:13:16: error: ‘NewSymbol’ is not a member of ‘v8::String’
   exports->Set(String::NewSymbol("parse"), FunctionTemplate::New(CreateFontFace)->GetFunction());
                ^
../src/freetype2.cc:13:80: error: no matching function for call to ‘v8::FunctionTemplate::New(void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’
   exports->Set(String::NewSymbol("parse"), FunctionTemplate::New(CreateFontFace)->GetFunction());
                                                                                ^
../src/freetype2.cc:13:80: note: candidate is:
In file included from /home/sh/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:134,
                 from ../src/freetype2.cc:1:
/home/sh/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/sh/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘void(const v8::FunctionCallbackInfo<v8::Value>&)’ to ‘v8::Isolate*’
In file included from ../src/freetype2.cc:1:0:
../node_modules/nan/nan.h: In instantiation of ‘void NanDisposePersistent(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&) [with T = v8::Object]’:
../node_modules/nan/nan.h:786:44:   required from here
../node_modules/nan/nan.h:394:5: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘Clear’
     handle.Clear();
     ^
make: *** [Release/obj.target/freetype2/src/freetype2.o] Error 1
make: Leaving directory `/home/sh/testfire/node_modules/freetype2/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/sh/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "node" "/home/sh/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sh/testfire/node_modules/freetype2
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/home/sh/.nvm/versions/node/v0.12.2/bin/node" "/home/sh/.nvm/versions/node/v0.12.2/bin/npm" "install" "freetype2"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! freetype2@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freetype2@0.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the freetype2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls freetype2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sh/testfire/npm-debug.log

**Comment by ericfreese** [comment]
Please try again with v0.2.x. Should be fixed.
